version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)  # Add root to Python path
      - pytest
artifacts:
  files:
    - '**/*'
