# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install
        run: make Install
      - name: Format (Black + isort)
        run: make format
      - name: Lint (pylint)
        run: make lint
      - name: Test (pytest + coverage)
        run: make test

